const SCREENS = {
  ONBOARDING: 'Onboarding',
  LOGIN: 'Login',
  SIGN_UP: 'SignUp',
  OTP: 'OTP',
  OTP_VERIFICATION: 'OTPVerify',
  PRODUCTS: 'Products',
  PRODUCT_DETAIL: 'ProductDetail',
  WISHLIST: 'Wishlist',
  CART: 'Cart',
  ADD_ADDRESS: 'AddAddress',
  CHECKOUT: 'Checkout',
  PAYMENT: 'Payment',
  ADD_CARD: 'AddCard',
  PAYMENT_FINAL: 'PaymentFinal',
  CHECKOUT_SUCCESS: 'CheckoutSuccess',
  CREATE_STORE: 'CreateStore',
  MY_STORE: 'MyStore',
  ADD_PRODUCT: 'AddProduct',
  MYSTORE_PRODUCTS: 'MyStoreProductScreen',
  STORE_PROFILE: 'StoreProfile',
  BEVERAGES: 'Beverages',
  BREADBAKERY: 'BreadBakery',
  VEGETABLE: 'Vegetable',
  FRUIT: 'Fruit',
  EGG: 'Egg',
  FROZENVEG: 'FrozenVeg',
  HOMECARE: 'HomeCare',
  PETCARE: 'PetCare',
  TRADLYSTORE:'TradlyStore',
  TRADLYSTORESEARCH:'TradlyStoreSearch',
  BOTTOM_NAVIGATOR: 'BottomNavigator',

  // BOTTOM_NAVIGATOR
  HOME: 'Home',
  BROWSE: 'Browse',
  STORE: 'Store',
  ORDER: 'Order',
  PROFILE: 'Profile',
};

export default SCREENS;
